from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path


CONTROL_CHARS_RE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")
IMAGE_RE = re.compile(r"!\[[^\]]*]\([^)]*\)\s*")
FIGURE_TOKEN = r"(?:文末)?彩?图\s*[\d一二三四五六七八九十百]+(?:[\s\u200a\u2009\u2005\u2003\u3000\-‑–—~～]*[\d一二三四五六七八九十百]+)*(?:[A-ZＡ-Ｚ])?"
FIGURE_LINE_RE = re.compile(rf"^\s*{FIGURE_TOKEN}(?:\s|$).+")
INLINE_FIGURE_RE = re.compile(
    rf"[（(]\s*(?:见|如)?\s*{FIGURE_TOKEN}(?:\s*[，,、]\s*{FIGURE_TOKEN})*\s*[）)]"
    rf"|(?:见|如)\s*{FIGURE_TOKEN}(?:\s*[，,、]\s*{FIGURE_TOKEN})*(?:所示)?"
    rf"|{FIGURE_TOKEN}(?:\s*[，,、]\s*{FIGURE_TOKEN})*"
)
TRAILING_PAGE_RE = re.compile(r"^(?P<title>.+?)(?:\s|\.|·|…){1,}(?P<page>\d{1,4})\s*$")
HEADING_PREFIX_RE = re.compile(r"^\s{0,3}#{1,6}\s*(?P<title>.+?)\s*$")


@dataclass
class SectionRecord:
    heading_level: int
    heading: str
    part: str
    chapter: str
    section: str
    subsection: str
    subsubsection: str
    page: int | None
    line_no: int


def main() -> None:
    parser = argparse.ArgumentParser(description="Clean MinerU/Markdown medical textbook files with rule-based heuristics.")
    parser.add_argument("input", nargs="?", help="Input markdown file.")
    parser.add_argument("-o", "--output", default=None, help="Output cleaned markdown path.")
    parser.add_argument("--input-dir", default=None, help="Clean every *.md file under this directory.")
    parser.add_argument("--output-dir", default=None, help="Output directory for --input-dir mode.")
    parser.add_argument(
        "--records-output",
        default=None,
        help="Optional JSONL path for heading records in single-file mode. Not generated by default.",
    )
    parser.add_argument(
        "--records-dir",
        default=None,
        help="Optional directory for heading record JSONL files in --input-dir mode. Not generated by default.",
    )
    parser.add_argument(
        "--keep-front-matter",
        action="store_true",
        help="Keep content before the detected main body. By default front matter and TOC are skipped.",
    )
    args = parser.parse_args()

    if args.input_dir:
        if not args.output_dir:
            parser.error("--output-dir is required when using --input-dir")
        summaries = clean_directory(
            input_dir=Path(args.input_dir),
            output_dir=Path(args.output_dir),
            records_dir=Path(args.records_dir) if args.records_dir else None,
            keep_front_matter=args.keep_front_matter,
        )
        print(json.dumps(summaries, ensure_ascii=False, indent=2))
        return

    if not args.input:
        parser.error("input markdown file is required unless --input-dir is used")

    input_path = Path(args.input)
    output_path = Path(args.output) if args.output else input_path.with_name(f"{input_path.stem}.clean.md")
    records_path = Path(args.records_output) if args.records_output else None

    summary = clean_file(
        input_path=input_path,
        output_path=output_path,
        records_path=records_path,
        keep_front_matter=args.keep_front_matter,
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))


def clean_file(
    input_path: Path,
    output_path: Path,
    records_path: Path | None = None,
    keep_front_matter: bool = False,
) -> dict:
    raw_text = input_path.read_text(encoding="utf-8", errors="replace")
    cleaned_text, records = clean_book_markdown(raw_text, keep_front_matter=keep_front_matter)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(cleaned_text, encoding="utf-8", newline="\n")
    if records_path is not None:
        records_path.parent.mkdir(parents=True, exist_ok=True)
        records_path.write_text(
            "\n".join(json.dumps(asdict(record), ensure_ascii=False) for record in records) + ("\n" if records else ""),
            encoding="utf-8",
            newline="\n",
        )

    return {
        "input": str(input_path),
        "output": str(output_path),
        "records_output": str(records_path) if records_path else None,
        "heading_records": len(records),
        "chars": len(cleaned_text),
    }


def clean_directory(
    input_dir: Path,
    output_dir: Path,
    records_dir: Path | None = None,
    keep_front_matter: bool = False,
) -> list[dict]:
    summaries = []
    for input_path in sorted(input_dir.rglob("*.md")):
        rel_path = input_path.relative_to(input_dir)
        if input_path.name.endswith(".clean.md"):
            continue
        output_path = output_dir / rel_path
        records_path = (records_dir / rel_path).with_suffix(".sections.jsonl") if records_dir else None
        summaries.append(
            clean_file(
                input_path=input_path,
                output_path=output_path,
                records_path=records_path,
                keep_front_matter=keep_front_matter,
            )
        )
    return summaries


def clean_book_markdown(text: str, keep_front_matter: bool = False) -> tuple[str, list[SectionRecord]]:
    lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    start_index = 0 if keep_front_matter else detect_body_start(lines)

    state = {
        "part": "",
        "chapter": "",
        "section": "",
        "subsection": "",
        "subsubsection": "",
    }
    output: list[str] = []
    records: list[SectionRecord] = []
    previous_blank = True
    in_table = False

    for raw_line_no, raw_line in enumerate(lines[start_index:], start=start_index + 1):
        line = normalize_line(raw_line)
        if is_empty_markdown_heading(line):
            continue
        if not line:
            if not previous_blank:
                output.append("")
                previous_blank = True
            continue

        if IMAGE_RE.search(line):
            line = IMAGE_RE.sub("", line).strip()
            if not line:
                continue

        table_like = is_table_line(line)
        if table_like:
            in_table = True
        elif in_table and not table_like:
            in_table = False

        if not in_table:
            line = normalize_spaces(line)
        if not line:
            continue

        heading = detect_heading(line, in_table=in_table)
        if heading:
            level, title, page = heading
            if should_merge_chapter_title(records, level, title):
                merge_chapter_title(output, records, state, title)
                previous_blank = False
                continue
            update_state(state, level, title)
            normalized_heading = f"{'#' * level} {title}".rstrip()
            append_with_blank(output, normalized_heading)
            records.append(
                SectionRecord(
                    heading_level=level,
                    heading=title,
                    part=state["part"],
                    chapter=state["chapter"],
                    section=state["section"],
                    subsection=state["subsection"],
                    subsubsection=state["subsubsection"],
                    page=page,
                    line_no=raw_line_no,
                )
            )
            previous_blank = False
            continue

        output.append(line)
        previous_blank = False

    cleaned = "\n".join(output).strip() + "\n"
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    return cleaned, records


def detect_body_start(lines: list[str]) -> int:
    normalized = [normalize_line(line) for line in lines]
    toc_index = next((idx for idx, line in enumerate(normalized) if strip_hash(line) == "目录"), -1)
    body_candidates: list[int] = []
    for idx, line in enumerate(normalized):
        title = strip_hash(line)
        if re.fullmatch(r"绪\s*论(?:\s+\d+)?", title):
            body_candidates.append(idx)
        elif re.fullmatch(r"第[一二三四五六七八九十百千万0-9]+章\s*$", title):
            body_candidates.append(idx)

    after_toc = [idx for idx in body_candidates if idx > toc_index]
    if len(after_toc) >= 2:
        return after_toc[1]
    if after_toc:
        return after_toc[0]
    return 0


def normalize_line(line: str) -> str:
    line = CONTROL_CHARS_RE.sub("", line)
    line = line.replace("�", "")
    line = line.replace("\u200b", "")
    line = line.replace("\ufeff", "")
    return line.rstrip()


def normalize_spaces(line: str) -> str:
    line = re.sub(r"[ \t\u3000]+", " ", line)
    line = re.sub(r"\s+([，。；：、！？])", r"\1", line)
    line = re.sub(r"([（(])\s+", r"\1", line)
    line = re.sub(r"\s+([）)])", r"\1", line)
    return line.strip()


def strip_hash(line: str) -> str:
    match = HEADING_PREFIX_RE.match(line)
    title = match.group("title") if match else line
    return normalize_spaces(title.strip())


def is_empty_markdown_heading(line: str) -> bool:
    return bool(re.fullmatch(r"\s*#{1,6}\s*", line))


def is_figure_caption(line: str) -> bool:
    return bool(FIGURE_LINE_RE.match(normalize_spaces(line)))


def remove_inline_figure_refs(line: str) -> str:
    line = INLINE_FIGURE_RE.sub("", line)
    line = re.sub(r"（\s*）|\(\s*\)", "", line)
    return line


def is_table_line(line: str) -> bool:
    stripped = line.strip()
    return stripped.startswith("|") and stripped.endswith("|") and stripped.count("|") >= 2


def detect_heading(line: str, in_table: bool = False) -> tuple[int, str, int | None] | None:
    if in_table:
        return None

    match = HEADING_PREFIX_RE.match(line)
    if not match:
        return None

    title = normalize_spaces(match.group("title"))
    if not title:
        return None

    title, page = split_trailing_page(title)
    title = cleanup_heading_title(title)
    if is_low_value_heading(title):
        return None

    level = classify_heading_level(title)
    if level is None:
        return None
    return level, title, page


def split_trailing_page(title: str) -> tuple[str, int | None]:
    match = TRAILING_PAGE_RE.match(title)
    if not match:
        return title, None
    page = int(match.group("page"))
    clean_title = normalize_spaces(match.group("title").rstrip(".·… "))
    return clean_title, page


def cleanup_heading_title(title: str) -> str:
    title = title.replace("|", " ")
    title = re.sub(r"\s+", " ", title)
    title = re.sub(r"^(第[一二三四五六七八九十百千万0-9]+章)\s*$", r"\1", title)
    return title.strip()


def is_low_value_heading(title: str) -> bool:
    low_value_patterns = (
        r"版权",
        r"图书在版编目",
        r"CIP",
        r"编委",
        r"主编简介",
        r"副主编简介",
        r"新形态教材",
        r"获取数字资源",
        r"读者信息反馈",
        r"修订说明",
        r"目录",
    )
    return any(re.search(pattern, title, re.I) for pattern in low_value_patterns)


def classify_heading_level(title: str) -> int | None:
    if re.match(r"^第[一二三四五六七八九十百千万0-9]+篇\b", title):
        return 1
    if re.match(r"^第[一二三四五六七八九十百千万0-9]+章\b", title):
        return 2
    if re.match(r"^绪\s*论$", title):
        return 2
    if re.match(r"^第[一二三四五六七八九十百千万0-9]+节\b", title):
        return 3
    if re.match(r"^[一二三四五六七八九十百千万]+[、.．]\s*\S+", title):
        return 4
    if re.match(r"^（[一二三四五六七八九十百千万]+）\s*\S+", title):
        return 5
    if re.match(r"^\(?\d+\)?[、.．]\s*\S+", title):
        return 6
    if len(title) <= 36 and not re.search(r"[。；！？]", title):
        return 4
    return None


def update_state(state: dict[str, str], level: int, title: str) -> None:
    if level == 1:
        state.update({"part": title, "chapter": "", "section": "", "subsection": "", "subsubsection": ""})
    elif level == 2:
        state.update({"chapter": title, "section": "", "subsection": "", "subsubsection": ""})
    elif level == 3:
        state.update({"section": title, "subsection": "", "subsubsection": ""})
    elif level == 4:
        state.update({"subsection": title, "subsubsection": ""})
    elif level >= 5:
        state.update({"subsubsection": title})


def append_with_blank(output: list[str], line: str) -> None:
    if output and output[-1] != "":
        output.append("")
    output.append(line)
    output.append("")


def should_merge_chapter_title(records: list[SectionRecord], level: int, title: str) -> bool:
    if level != 4 or not records:
        return False
    previous = records[-1]
    if previous.heading_level != 2:
        return False
    if not re.fullmatch(r"第[一二三四五六七八九十百千万0-9]+章", previous.heading):
        return False
    if re.search(r"[。；！？]", title) or len(title) > 40:
        return False
    return True


def merge_chapter_title(
    output: list[str],
    records: list[SectionRecord],
    state: dict[str, str],
    title: str,
) -> None:
    previous = records[-1]
    merged = f"{previous.heading} {title}"
    previous.heading = merged
    previous.chapter = merged
    state.update({"chapter": merged, "section": "", "subsection": "", "subsubsection": ""})

    for idx in range(len(output) - 1, -1, -1):
        if output[idx].strip():
            output[idx] = f"## {merged}"
            break


if __name__ == "__main__":
    main()
